#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Author: Hardy.zheng <wei.zheng@yun-idc>
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

"""Command line tool for creating meter for cds.
"""

import sys

from cds.cli import api

if __name__ == '__main__':
    sys.exit(api())
